### ISSUE TITLE
Upgrade to v.zero API and adding PayPal integration

### ISSUE THREAD

**Issue by henri-hulski** [henri-hulski/cartridge_braintree#2]
I have upgraded cartridge_braintree to the v.zero API and added PayPal as optional payment method.
Actually rewriting most of the app.
I also used some code from cartridge-pinpayments.
You can find it at https://github.com/henri-hulski/cartridge_braintree/tree/v.zero, which is the v.zero branch.

If you want I can make a PR here or if you prefer I can maintain it on my account.
I think in this case we have to make a transfer.

I have turned it also in a full Pypi package.
For now I have uploaded it to testpypi and you can install it with
`pip install -i https://testpypi.python.org/pypi cartridge_braintree`
or with utf-8 sorting support for country names with
`pip install -i https://testpypi.python.org/pypi cartridge_braintree[countries_utf8_sorting]`

Please take a look and tell me what you think.
Regards,
Henri

**Comment by molokov** [comment]
Happy to transfer it to you - I'm not actively maintaining or using Braintree any more.

I'll try to see if I can make your repo the main one.

**Comment by molokov** [comment]
It appears I can't transfer it using Github's methods because you already have a fork... not sure how to resolve this, will do some research.

**Comment by henri-hulski** [comment]
Maybe I can delete my fork before transfer. 
Am 20.01.2016 23:41 schrieb molokov notifications@github.com:It appears I can't transfer it using Github's methods because you already have a fork... not sure how to resolve this, will do some research.

**Comment by henri-hulski** [comment]
Actually I have deleted my fork. 
So if you want, you can transfer it. 
But I just see, that you updated the README. 
So if you prefer we can leave this repository untouched and I just upload it again to my account.

**Comment by molokov** [comment]
I'll attempt a transfer. Please add me as a collaborator if it works and you can take ownership :)

**Comment by henri-hulski** [comment]
Sure and thanks.

**Comment by henri-hulski** [comment]
I just found this in the Github help:

```
The original owner of the repository is added as a collaborator on the transferred repository.
```

So I think there is nothing I have to do with it.

**Comment by molokov** [comment]
Thanks :) I've updated the link in cartridge's README to point to your repo now.
I'll leave you to merge your branch and close this issue.

**Comment by henri-hulski** [comment]
Thanks :-)
I have merged my changes and uploaded this version to pypi. 

I have another question about the license. Here you use the MIT license but in cartridge-pinpayments you use a BSD license, which is more consistent with the licenses of Cartridge, Mezzanine and Django. 

So I would propose to change the license to the one you use for cartridge-pinpayments and enhance the copyright to 

```
'Copyright (c) Danny Sag, Henri Hulski and individual contributors.' 
```

What you think about it?

**Comment by molokov** [comment]
Sure, sounds good.

**Comment by henri-hulski** [comment]
I have updated the license and released a first beta release, which is also uploaded to PyPI. 
So you can install it with:

```
pip install cartridge_braintree
```

or with utf-8 sorting:

```
pip install cartridge_braintree[countries_utf8_sorting]
```

I have tested it with Braintree sandbox and everything worked fine. 
Not yet tested in production. 
So I think we still need some more testing. 

Will close this for now.
